In [4]:
# variables
# descriptivas l=4 
# comienzan por una letra (4l=8)
# no usan caracteres especiales (l$=8)
# correcto
# casting
# el nombre de una variable lleva letras y números y algunos simbolos _
# el nombre sea descriptivo
nombre_persona='Pedro' # cadena de caracteres
# area=lado*lado esto es error porque no esta definido aún
altura=3 # de tipo flotante, haciendo un casting
lado=5.0 # esto es un flotante directo
# lado*=4 esto es un error
# operadores *,/,+,- (aritméticos) >,<
area=lado*lado
print(area)
base=3
area=base*altura/2.0
print(area)
print(nombre_persona)

25.0
4.5
Pedro


In [5]:
# control de flujo de programa
temperaturaPersona=38
if temperaturaPersona>37:
    print('Tiene coronavirus')
print('cuidémonos todos')

if temperaturaPersona>37:
    print('Tiene coronavirus')
else:
    print('Esta saludable')

if temperaturaPersona<20:
    print('ya se petateo')
elif temperaturaPersona<28&temperaturaPersona>25:
    print('Esta saludable')
else:
    print('tiene coronavirus')

# if anidado
nacionalidad='mexicano'
if temperaturaPersona>37:
    print('Tiene coronavirus')
    if nacionalidad=='gringo':
        print('repatriarlo')
    else:
        print('cuarentena')
else:
    print('Esta saludable')


Tiene coronavirus
cuidémonos todos
Tiene coronavirus
tiene coronavirus
Tiene coronavirus
cuarentena


In [ ]:
# ejercicios de condiciones
# dividir A/B validando que B no sea cero
# calcule cuantos segundos hay en m dias, n horas y o minutos
# dada una cantidad en pesos, indique cuantos billetes de a 500 y cuantos de 200, de 100 y monedas debe dar el cajero


temperatura10
temperatura15
temperatura25
temperatura30
clima encendido


In [5]:
# ciclo
# imprime los número del 0 al 4
for i in range(5):
    print(i)
# imprime los número del 2 al 4
for i in range(2,5):
    print(i)
# imprime los números del 2 al 10 con incrementos de 2
for i in range(2,10,2):
    print(i)
# se usan cuando uno conoce de forma precisa el número de repeticiones

0
1
2
3
4
2
3
4
2
4
6
8


In [6]:
# ciclos anidados
for i in range(4):
    for j in range(4):
        print(i,j)

# ejercicios 
# convertidor de números entre diferentes bases

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(2, 0)
(2, 1)
(2, 2)
(2, 3)
(3, 0)
(3, 1)
(3, 2)
(3, 3)


In [7]:
# ciclos anidados
for i in range(1,11):
    for j in range(1,11):
        print(i,j,i*j)
        

(1, 1, 1)
(1, 2, 2)
(1, 3, 3)
(1, 4, 4)
(1, 5, 5)
(1, 6, 6)
(1, 7, 7)
(1, 8, 8)
(1, 9, 9)
(1, 10, 10)
(2, 1, 2)
(2, 2, 4)
(2, 3, 6)
(2, 4, 8)
(2, 5, 10)
(2, 6, 12)
(2, 7, 14)
(2, 8, 16)
(2, 9, 18)
(2, 10, 20)
(3, 1, 3)
(3, 2, 6)
(3, 3, 9)
(3, 4, 12)
(3, 5, 15)
(3, 6, 18)
(3, 7, 21)
(3, 8, 24)
(3, 9, 27)
(3, 10, 30)
(4, 1, 4)
(4, 2, 8)
(4, 3, 12)
(4, 4, 16)
(4, 5, 20)
(4, 6, 24)
(4, 7, 28)
(4, 8, 32)
(4, 9, 36)
(4, 10, 40)
(5, 1, 5)
(5, 2, 10)
(5, 3, 15)
(5, 4, 20)
(5, 5, 25)
(5, 6, 30)
(5, 7, 35)
(5, 8, 40)
(5, 9, 45)
(5, 10, 50)
(6, 1, 6)
(6, 2, 12)
(6, 3, 18)
(6, 4, 24)
(6, 5, 30)
(6, 6, 36)
(6, 7, 42)
(6, 8, 48)
(6, 9, 54)
(6, 10, 60)
(7, 1, 7)
(7, 2, 14)
(7, 3, 21)
(7, 4, 28)
(7, 5, 35)
(7, 6, 42)
(7, 7, 49)
(7, 8, 56)
(7, 9, 63)
(7, 10, 70)
(8, 1, 8)
(8, 2, 16)
(8, 3, 24)
(8, 4, 32)
(8, 5, 40)
(8, 6, 48)
(8, 7, 56)
(8, 8, 64)
(8, 9, 72)
(8, 10, 80)
(9, 1, 9)
(9, 2, 18)
(9, 3, 27)
(9, 4, 36)
(9, 5, 45)
(9, 6, 54)
(9, 7, 63)
(9, 8, 72)
(9, 9, 81)
(9, 10, 90)
(10, 1, 10)
(10, 2, 20)


In [9]:
# ciclos
temperatura=0
while temperatura<30:
    temperatura=int(input('temperatura'))
    print('clima agradable')
print('enfriando')




temperatura5
clima agradable
temperatura30
clima agradable
enfriando


In [13]:
#10 a binario
#10/2=5,0
#5/2=2,1
#2/2=1, 0
#1/2=0,1
#10=1010
decimal=20
while decimal>0:
    residuo=decimal%2
    decimal=decimal/2
    print(decimal,residuo)
# tarea convertir de decimal a octal, decimal a hexadecimal
# resolver un sistema de ecuaciones por gauss-seidel, 
# encontrar el cruce por cero de una ecuación: bisección, newton, punto medio

(10, 0)
(5, 0)
(2, 1)
(1, 0)
(0, 1)


In [8]:
# método de bisección
import math
x1=-1.0
x2=-0.2
error=1000000.0
while error>0.0001:
    xm=(x1+x2)/2
    error=abs(x1-xm)
    fx1=4*math.pow(x1,2)+3*x1
    fx2=4*math.pow(x2,2)+3*x2
    fxm=4*math.pow(xm,2)+3*xm
    print(x1,x2,xm)
    if fxm*fx1<0:
        x2=xm
    else:
        x1=xm

hola mundo
-1.0 -0.2 -0.6
-1.0 -0.6 -0.8
-0.8 -0.6 -0.7
-0.8 -0.7 -0.75
-0.75 -0.7 -0.725
-0.725 -0.7 -0.7124999999999999
-0.7124999999999999 -0.7 -0.7062499999999999
-0.7062499999999999 -0.7 -0.703125
-0.703125 -0.7 -0.7015625
-0.7015625 -0.7 -0.7007812499999999
-0.7007812499999999 -0.7 -0.7003906249999999
-0.7003906249999999 -0.7 -0.7001953125
-0.7001953125 -0.7 -0.70009765625


In [ ]:
# a=4, b=8, c=7
# imprimir el menor de estos tres numeros


In [4]:
binario=['1','0','0'] # lista
contador=4
acumulador=0
for i in binario:
    print(i,contador)
    acumulador+=int(i)*contador
    contador/=2
print(sumador)
    

1 4
0 2.0
0 1.0


NameError: name 'sumador' is not defined

In [42]:
# convertidor de binario a hexadecimal
cadena="1001"
print(cadena[2], len(cadena))
numBinario="111101001"
#numBinario=[1,1,1,1,0,1,0,0,1]
sobra=len(numBinario)%4
numciclos=int((len(numBinario)/4))
if sobra>0:
    numciclos+=1
inicial=4
final=0
for i in range(numciclos):
    if i==0:
        numhex=numBinario[-inicial:]
    else:
        numhex=numBinario[-inicial:-final]
    inicial+=4
    final+=4
    print(numhex)
    if numhex==[0,0,0,0]:
        print(0)
    if numhex==[0,0,0,1]:
        print(1)
    if numhex==[0,0,1,0]:
        print(2)
    if numhex==[0,0,1,1]:
        print(3)
    if numhex==[0,1,0,0]:
        print(4)
    if numhex==[0,1,0,1]:
        print(5)
    if numhex==[0,1,1,0]:
        print(6)
#for i in numBinario:
#    print(i)

('0', 4)
1001
1110
1


In [6]:
# matrices de una dimension
import numpy as np
vector1=np.array([1,2,3])
vector2=np.array([4,5,6])
print(vector1.shape,vector1.dtype)
multi=np.zeros(3)
suma=np.array([0,0,0])
# accesando un valor
print(vector1[1])
# multiplicacion de un vector
for i in range(3):
    multi[i]=vector1[i]*4
print(multi)

for i in range(0,3):
    suma[i]=vector1[i]+vector2[i]
print(suma)
    
# suma de los elementos
# sumador i vector[i] sumador+=vector[i]
#   0
#   0     0  1        1
#   1     1  2        3
#   3     2  3        6
sumador=0
for i in range(3):
    sumador+=vector1[i]
print(sumador)
# calcula el maximo
maximo=0
for i in range(3):
    if vector1[i]>maximo:
        maximo=vector1[i]
print(maximo)

print(vector1*vector2.transpose())


(3,) int64
2
[ 4.  8. 12.]
[5 7 9]
6
3
[ 4 10 18]


In [9]:
# indexing
import numpy as np
m1=np.array([1,2,3,4,5,6])
# accesando a un elemento
print(m1[3])
# accesando a los elementos 2,3 y 4
print(m1[2:4])
# accesando a todos los primeros elementos hasta la posición 3
print(m1[:3])

4
[3 4]
[1 2 3]


In [14]:
# matrices de dos dimensiones
import numpy as np
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m,m.shape)
print(m[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
5


In [18]:
# matrices de dos dimensiones
# suma de las columnas y renglones
# suma de la diagonal principal
# solucion de ecuaciones de gauss y gauss-jordan
# suma y multiplicacion de dos matrices

In [8]:
# solución de un sistema de ecuaciones por el método de Gauss
from numpy import *
m=array([[3,1,1,2],[5,1,-4,1],[7,1,2,3]])
for i in range(2):
    for j in range(i+1,3):
        for k in range(4):
            m[j][k]=m[i][i]*m[j][k]-m[j][i]*m[i][k]
print(m)

[[  3   1   1   2]
 [  0   3 -12   3]
 [  0   0  18  27]]


In [7]:
# solución de ecuaciones por gauss-seidel
errordeseado=.001
errorcalculadox1=1000
errorcalculadox2=1000
errorcalculadox3=1000
x1=0.0
x2=0.0
x3=0.0
iteracion=0
while errorcalculadox1>errordeseado and errorcalculadox2>errordeseado and errorcalculadox3>errordeseado:
    x1n=(7.85+0.1*x2+0.2*x3)/3
    x2n=(-19.3-0.1*x1n+0.3*x3)/7
    x3n=(71.4-0.3*x1n+0.2*x2n)/10
    errorcalculadox1=abs((x1n-x1)/x1n)
    errorcalculadox2=abs((x2n-x2)/x2n)
    errorcalculadox3=abs((x3n-x3)/x3n)
    print(errorcalculadox1,errorcalculadox2,errorcalculadox3)
    x1=x1n
    x2=x2n
    x3=x3n
    iteracion+=1
    print(x1,x2,x3)
    if iteracion>100:
        break

(1.0, 1.0, 1.0)
(2.6166666666666667, -2.7945238095238096, 7.005609523809525)
(0.1250234998996312, 0.11797736136506948, 0.0007597845414304334)
(2.990556507936508, -2.499624684807256, 7.00029081106576)


In [17]:
# listas y diccionarios
listavacia=[]
marcasautos=['nissan','ford','volkswagen']
marcasautos.append('kia')
print(marcasautos[2])
for i in marcasautos:
    print(i)
diccionariovacio={}
diccionarioautos={'nissan':['tsuru','tiida'],'ford':['focus'],'volkswagen':['jetta','vento']}
# agregando datos al diccionario
diccionarioautos['kia']=['rio']
# acceso a las llaves
for llave in diccionarioautos:
    print(llave)
# acceso a los valores de cada llave
for valores in diccionarioautos.values():
    print(valores)
# acceso a los valores de una llave
print(diccionarioautos['ford'])

volkswagen
nissan
ford
volkswagen
kia
nissan
volkswagen
kia
ford
['tsuru', 'tiida']
['jetta', 'vento']
['rio']
['focus']
['focus']


In [16]:
# funciones
def sumar(a,b):
    resultado=a+b
    return resultado

print(sumar(4,3),sumar(5,8))

7 13


In [8]:
# funciones y funciones lambda
def calculaerror(valor1,valor2):
    error=abs((valor1-valor2)/valor1)
    return error
errordeseado=.001
errorcalculadox1=1000
errorcalculadox2=1000
errorcalculadox3=1000
x1=0.0
x2=0.0
x3=0.0
iteracion=0
while errorcalculadox1>errordeseado and errorcalculadox2>errordeseado and errorcalculadox3>errordeseado:
    x1n=(7.85+0.1*x2+0.2*x3)/3
    x2n=(-19.3-0.1*x1n+0.3*x3)/7
    x3n=(71.4-0.3*x1n+0.2*x2n)/10
    errorcalculadox1=calculaerror(x1n,x1)
    errorcalculadox2=calculaerror(x2n,x2)
    errorcalculadox3=calculaerror(x3n,x3)
    print(errorcalculadox1,errorcalculadox2,errorcalculadox3)
    x1=x1n
    x2=x2n
    x3=x3n
    iteracion+=1
    print(x1,x2,x3)
    if iteracion>100:
        break

(1.0, 1.0, 1.0)
(2.6166666666666667, -2.7945238095238096, 7.005609523809525)
(0.1250234998996312, 0.11797736136506948, 0.0007597845414304334)
(2.990556507936508, -2.499624684807256, 7.00029081106576)


In [16]:
global b
def sumar(a):
    global b
    b=3
    print(a+b)
numero=5
sumar(numero)
print(b)

8
3


In [18]:
# funciones lambda
sumar= lambda a:a+3
restar=lambda a,b:a-b
print(sumar(5))
print(restar(7,3))
# 10 ejercicios con funciones comunes y 10 con funciones lambda

8
4


In [ ]:
# manejo de archivos

In [11]:
# c(0,0)=a(0,0)+b(0,0) c(0,1)=a(0,1)+b(0,1) a(0,2)+b(0,2)
# a(1,0)+b(1,0) a(1,1)+b(1,1) a(1,2)+b(1,2)
import numpy as np
sumar= lambda a,b:a+b
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=np.zeros([2,3])
for renglon in range(2):
    for columna in range(3):
        c[renglon][columna]=sumar(a[renglon][columna],b[renglon][columna])
        #c[renglon][columna]=a[renglon][columna]+b[renglon][columna]
        print(renglon,columna)
print(c)

0 0
0 1
0 2
1 0
1 1
1 2
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [17]:
# pivotes 0,0 1,1 2,2
# pivote (0,0) elementos abajo:4,7 (1,0)(2,0)
# pivote(1,1) elementos abajo:8 (2,1)
import numpy as np
m=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(m)
renglon,columna=m.shape
# ceros los elementos abajo de la diagonal principal
for i in range(renglon):
    print(m[i][i])
    for j in range(i+1,renglon):
        print(i,j)
        print(m[j][i])
# hacer ceros los elementos arriba de la diagonal principal
# pivotes 0,0 1,1 2,2
#pivote 0,0
# pivote (1,1), elementos arriba: 2 (0,1)
# pivote (2,2), elementos arriba: 3,6 (0,2) (1,2)
for i in range(renglon):
    for j in range(0,i):
        print(i,j)
        print(m[j][i])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
1
0 1
4
0 2
7
5
1 2
8
9
1 0
2
2 0
3
2 1
6


In [4]:
# primera generación
# programas cortos
# difíciles de actualizar

# segunda generación
# programación estructurada
# sencillo de entender
# programas grandes son complejos
# no reutilización de código, herencia, abstracción

# Programación orientada a objetos
# si reutilización de código, herencia, abstracción
# forma de pensar diferente (objetos: pelota)
class llanta:
    # constructor
    def __init__(self):
        # atributos
        self.diametro=15
        self.presion=30
    def __repr__(self):
        return 'mi llanta tiene un diametro de {} y una presion de {}'.format(self.diametro,self.presion)
    # métodos
    def get_presion(self):
        return self.presion
    def valores(self):
        """
        esta es la ayuda del método valores
        """
        print(self.diametro,self.presion)
        
    def inflar(self, valorpresion):
        self.presion=valorpresion
# objeto
goodyear=llanta() 
print(goodyear)
help(goodyear.valores)
# imprime los valores asignados por el constructor
goodyear.valores()
presion=goodyear.get_presion()
print(presion)
# llama el método y modifica una propiedad
goodyear.inflar(100)
# imprime los atributos después de ser modificados por un método
goodyear.valores()
# crea un nuevo objeto
firestone=llanta()
firestone.valores()
#firestone.inflar(15)

mi llanta tiene un diametro de 15 y una presion de 30
Help on method valores in module __main__:

valores() method of __main__.llanta instance
    esta es la ayuda del método valores

15 30
30
15 100
15 30


In [7]:
# pelota
import numpy as np
class pelota:
    def __init__(self):
        # constructor
        # propiedades
        self.presion=8.0
        self.valores_validos=np.array([10,20,30])
        self.numero_paneles=4
    # métodos
    def set_presion(self,valor):
        if valor>50:
            print('no es posible')
        else:
            for i in self.valores_validos:
                if i==valor:
                    self.presion=valor
    def get_presion(self):
        return self.presion
    def rebota(self):
        print('estoy rebotando')
    def inflar(self):
        pass

# se crea el objeto
pelota1=pelota()
# mando a llamar un método del objeto
pelota1.rebota()
# esto no se debe hacer
print(pelota1.presion)
pelota1.presion=10
print(pelota1.presion)
# la forma correcta
pelota1.set_presion(20)
print(pelota1.get_presion())
pelota2=pelota()
pelota2.rebota()

estoy rebotando
8.0
10
20
estoy rebotando


In [5]:
# herencia
class pelota:
    def __init__(self):
        self.presion=10
class volleyball(pelota):
    pass
mibalon=volleyball()
print(mibalon.presion)

10


In [9]:
class llanta:
    def __init__(self):
        self.diametro=15
        self.presion=30
        self.temperatura=36
    def get_presion(self):
        return self.presion
    def valores(self):
        print(self.diametro,self.presion)
        
    def inflar(self, valorpresion):
        self.presion=float(valorpresion)

# simulacion
# vectores de simulacion, uno o mas por cada caso
valoresdepresion=[10,30,25]
goodyear=llanta() 
# análisis del comportamiento por cada vector de simulacion
for i in valoresdepresion:
    # no recomendable
    gooyear.presion=i
    # recomendable
    goodyear.inflar(i)
    print(goodyear.get_presion)
    if goodyear.get_presion()<30:
        print('llanta ponchada')
    else:
        print('llanta en buen estado')

10
llanta ponchada
30
llanta en buen estado
25
llanta ponchada


In [ ]:
# manejo de pandasv

In [1]:
# arreglos con numpy
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<type 'numpy.ndarray'>
(3,)
(1, 2, 3)
[5 2 3]
(2, 3)
(1, 2, 4)


In [2]:
# creando arreglos con numpy
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.17852102 0.62203921]
 [0.11056903 0.63879188]]


In [3]:
# slicing in numpy
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [4]:
# Integer array indexing
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

(array([5, 6, 7, 8]), (4,))
(array([[5, 6, 7, 8]]), (1, 4))
(array([ 2,  6, 10]), (3,))
(array([[ 2],
       [ 6],
       [10]]), (3, 1))


In [5]:
# boolean array indexing
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [6]:
# datatypes
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"


int64
float64
int64


In [9]:
# array math
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
10
[4 6]
[3 7]


In [ ]:
#Transpuesta
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

In [11]:
# broadcasting
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [13]:
from scipy.misc import imread, imsave, imresize, imageio

# Read an JPEG image into a numpy array
img = imageio.imread('assets/cat.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', img_tinted)


ImportError: cannot import name imageio

In [9]:
# fecha, temperatura, humedad
# 6/11/2020,30,15
# 
import pandas as pd
data = pd.read_csv("dataall.csv") 
# muestra los nombres de las columnas
print('nombre de columnas',data.columns)
# pone nombres a las columnas
data.columns=['latitud', 'longitud', 'maximo', 'distancia']
print(data.columns)
# imprime los primeros datos
print(data.head())
# ordena los datos tomando como referencia una columna en orden ascendente
data.sort_values(by=['distancia'], inplace=True)
print(data.head())
# ordena los datos en forma descendente
data.sort_values(by=['distancia'], inplace=True,  ascending=False)
print(data.head())
# ordena por varias columnas
data.sort_values(by=['maximo','distancia'], inplace=True)
print(data.head())
# accesando a los datos de una columna
print(data['longitud'])
# accesando ciertos renglones
print(data[600:605])
# accesando un dato en particular
print(data.loc[601])
print(data.loc[601, 'maximo'])
# indices booleanos
print(data[data['distancia']>30])


nombre de columnas Index(['16.5656683333', '-93.022155', '23', '0'], dtype='object')
Index(['latitud', 'longitud', 'maximo', 'distancia'], dtype='object')
     latitud   longitud  maximo  distancia
0  16.565668 -93.022155     152        0.0
1  16.565668 -93.022155     149        0.0
2  16.563968 -93.024222      23      291.0
3  16.563968 -93.024222     154        0.0
4  16.563968 -93.024222     153        0.0
       latitud   longitud  maximo  distancia
0    16.565668 -93.022155     152        0.0
586  16.344310 -93.758547     114        0.0
587  16.344310 -93.758547      15        0.0
588  16.344310 -93.758547     129        0.0
589  16.344310 -93.758547      19        0.0
       latitud   longitud  maximo  distancia
933  16.533677 -93.028960      23     3899.0
918  16.475477 -93.043037     159     3792.0
911  16.449330 -93.065885     149     3755.0
165  16.311103 -93.234922      19     3612.0
404  16.203188 -93.968747      30     3573.0
       latitud   longitud  maximo  distancia
60

In [ ]:
# tipos de datos particulares
# estructuras de datos para almacenamiento de información
# pila: los datos se recuperan en orden inverso de como fueron introducidos (LIFO)
# cola: los datos se recuperan en el orden en que fueron introducidos (FIFO)
# pila.push(5) 
# pila.push(3)
# pila.pop() # me devuelve el 3
# pila.pop() # me devuelve el 5
# pila.pop() # no devuelve nada
# cola.push(5)
# cola.push(3)
# cola.pop() # me devuelve el 5

In [12]:
import numpy as np
class pila():
    def __init__(self,tamanio_pila):
        self.datos_en_pila=0
        self.mis_datos=np.zeros((tamanio_pila))
    def push(self,dato):
        self.mis_datos[self.datos_en_pila]=dato
        self.datos_en_pila+=1
    def pop(self):
        valor_a_devolver=self.mis_datos[self.datos_en_pila-1]
        self.datos_en_pila-=1
        return valor_a_devolver
mipila=pila(20)
mipila.push(5)
mipila.push(3)
print(mipila.pop())
print(mipila.pop())
print(mipila.pop())


3.0
5.0
0.0


In [ ]:
# árbol binario, árbol genealógico
#              1
#           2      3
#         4   5  6   7
# primero profundidad: 1,2,4,5,3,6,7
# primero en anchura: 1,2,3,4,5,6,7
# dominó
# se inicia con la mula de 6
# cuantos hijos tendría el nodo? 6,0 6,1 6,2
# en el árbol almacenarias las fichas

In [15]:
import numpy as np
class arbol():
    def __init__(self):
        self.red=np.zeros((5,3))
        self.contador=0
        self.red_diccionario={}
    def agregar(self,nodo_origen,nodo_izquierda,nodo_derecha):
        self.red_diccionario[nodo_origen]=[nodo_izquierda,nodo_derecha]
        self.red[self.contador,0]=nodo_origen
        self.red[self.contador,1]=nodo_izquierda
        self.red[self.contador,2]=nodo_derecha
        self.contador+=1
    def muestra_red(self):
        print(self.red)
        print(self.red_diccionario)
    def anchura(self):
        print('1')
        print(self.red_diccionario[1])
        print(self.red_diccionario[2])
        print(self.red_diccionario[3])
        print(self.red[0,0])
        print(self.red[0,1])
        print(self.red[0,2])
        print(self.red[1,1])
        print(self.red[1,2])
        print(self.red[2,1])
        print(self.red[2,2])
        for i in range(3):
            print(self.red[0,i])
        for i in range(1,3):
            for j in range(1,3):
                print(self.red[i,j])
miarbol=arbol()
miarbol.agregar(1,2,3)
miarbol.agregar(2,4,5)
miarbol.agregar(3,6,7)
miarbol.muestra_red()
miarbol.anchura()

[[1. 2. 3.]
 [2. 4. 5.]
 [3. 6. 7.]
 [0. 0. 0.]
 [0. 0. 0.]]
{1: [2, 3], 2: [4, 5], 3: [6, 7]}
1
[2, 3]
[4, 5]
[6, 7]
1.0
2.0
3.0
4.0
5.0
6.0
7.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0


In [12]:
# árbol múltiple
# 1
# 2          3          4
# 5          7
# 6 3        
# 1, 2 3 4 , 5 7, 6 3 
# matriz
# padre hijo
# 1     2
# 1     3
# 1     4
# 2     5
# 3     7
# 5     6
import numpy as np
class red():
    def __init__(self):
        self.matriz=np.zeros((6,2))
        self.apuntador=0
    def llenar(self,padre,hijo):
        self.matriz[self.apuntador,0]=padre
        self.matriz[self.apuntador,1]=hijo
        self.apuntador+=1
    def mostrar(self):
        print(self.matriz)
    def anchura(self):
        nodo_principal=self.matriz[0,0]
        print(nodo_principal)
        lista_hijos=[]
        # primer nivel
        for i in range(self.apuntador):
            if self.matriz[i,0]==nodo_principal:
                print(self.matriz[i,1])
                lista_hijos.append(self.matriz[i,1])
        # segundo nivel
        for hijo in lista_hijos:
            for i in range(self.apuntador):
                if self.matriz[i,0]==hijo:
                    print(self.matriz[i,1])
                    lista_hijos.append(self.matriz[i,1])
        # nivel pro
        print('nivel pro')
        lista_hijos_pro=[]
        lista_hijos_pro.append(nodo_principal)
        print(nodo_principal)
        for k in range(3):
            for hijo in lista_hijos_pro:
                lista_nietos=[]
                for i in range(self.apuntador):
                    if self.matriz[i,0]==hijo:
                        print(self.matriz[i,1])
                        lista_nietos.append(self.matriz[i,1])
                lista_hijos_pro=lista_nietos
                
mired=red()
mired.llenar(1,2)
mired.llenar(1,3)
mired.llenar(1,4)
mired.llenar(2,5)
mired.llenar(3,7)
mired.llenar(5,6)
mired.mostrar()
mired.anchura()

[[1. 2.]
 [1. 3.]
 [1. 4.]
 [2. 5.]
 [3. 7.]
 [5. 6.]]
1.0
2.0
3.0
4.0
5.0
7.0
6.0
nivel pro
1.0
2.0
3.0
4.0
5.0
7.0


In [ ]:
# juego: dominó, baraja, damas inglesas, ajedrez

In [ ]:
# proyecto mecatrónico